binop_separator = "front"
blank_lines_upper_bound = 1
brace_style = "SameLineWhere"
combine_control_expr = true
fn_args_layout = "Tall"
fn_single_line = true
format_strings = true
indent_stlye = "Block"
match_arm_leading_pipes = "Preserve"
match_block_trailing_comma = true
imports_granularity = "Module"
newline_style = "Unix"
overflow_delimited_expr = true
group_imports = "StdExternalCrate"
space_after_colon = true
space_before_colon = false
tap_spaces = 4
trailing_comma = "Vertical"
trailing_semicolon = false
unstable_features = false
use_small_heuristics = "Max"
wrap_comments = true
